<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CourseResource\Pages;
use App\Filament\Resources\CourseResource\RelationManagers\SessionsRelationManager;
use App\Filament\Resources\CourseResource\RelationManagers\StudiesRelationManager;
use App\Filament\Resources\CourseResource\RelationManagers\UsersRelationManager;
use App\Models\Course;
use App\Models\Lang;
use Filament\Forms;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class CourseResource extends Resource
{
    protected static ?string $model = Course::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function getLabel(): ?string
    {
        return __('headers.course'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('headers.course'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return __('headers.courses'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('headers.courses'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Card::make()->schema([
                    Tabs::make('Label')
                        ->tabs(
                            function () {
                                $items = [];
                                foreach (Lang::whereIsActive(true)->get() as $lang) {
                                    array_push($items,
                                        Tabs\Tab::make($lang->name)
                                            ->schema([
                                                Forms\Components\TextInput::make("title." . $lang->code)->label(__("words.title"))->required(),
                                                Forms\Components\Textarea::make("description." . $lang->code)->label(__("words.description"))->required(),
                                            ]),
                                    );
                                }
                                return $items;
                            }
                        ),
                    SpatieMediaLibraryFileUpload::make('image')->collection('image')->label(__("words.image")),
                    Forms\Components\TextInput::make("duration")->label(__("words.duration"))->numeric()->required(),
                    Forms\Components\TextInput::make("price")->label(__("words.price"))->numeric()->required(),
                    Forms\Components\Select::make("category_id")->options(
                        fn() => \App\Models\Category::all()->pluck("name", "id")
                    )->required()->label(__("words.category"))
                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make("title")->sortable()->label(__('words.title'))->searchable(),

                Tables\Columns\TextColumn::make('studies_count')->counts('studies')
                    ->badge()->color("danger")->label(__('headers.studies')),


                Tables\Columns\TextColumn::make("category.name")->sortable()
                    ->badge()->label(__('words.category'))->searchable(),
                Tables\Columns\TextColumn::make("price")->sortable()->label(__('words.price')),
                Tables\Columns\TextColumn::make("duration")->sortable()->label(__('words.duration')),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            StudiesRelationManager::class,
            UsersRelationManager::class,
        ];
    }


    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCourses::route('/'),
            'create' => Pages\CreateCourse::route('/create'),
            'edit' => Pages\EditCourse::route('/{record}/edit'),
        ];
    }
}
