<?php

namespace App\Models;

use App\Enums\UserTypeEnum;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use PhpParser\Builder;

class Teacher extends User
{
    use HasFactory;

    protected $table = "users";


    protected static function booted()
    {
        static::addGlobalScope('type', function (\Illuminate\Database\Eloquent\Builder $builder) {
            $builder->whereMonth('type', UserTypeEnum::TEACHER->value);
        });
        parent::booted(); // TODO: Change the autogenerated stub
    }
}
